### PR TITLE
Port to laravel 5

### PR DESCRIPTION
**Pull request by luukholleman**
As the title says, ported to Laravel 5

### CODE REVIEW

**Comment by luukholleman** [comment]
I will check if i can fix it

**Comment by luukholleman** [comment]
Fixed the unit tests (except 1), the first unit test always throws this error. But since this error is in Laravel itself i can't do much about it other then making a pull request to Laravel.

**Comment by nqxcode** [comment]
Can you try to update "orchestra/testbench"? In composer.json "orchestra/testbench": "3.0.*"

**Comment by luukholleman** [comment]
I updated and converted some code that no longer worked. I have not much experience with the ioc and facades features so you should check if i'm not doing anything unnecessary.

**Pull request merged**
